### ISSUE TITLE
Compatibility with Android Studio 3.2.1

### ISSUE THREAD

**Issue by edityomurti** [OlivierMary/aw-watcher-jetbrains#2]
Hi Olivier,

Does this plugin compatible with Android Studio 3.2.1?

I try to install this plugin from disk because this plugin not available in "Install JetBrains plugin.." and "Browse repositories..." 
I already tried to select the `zip` and `jar` file,  then I got error message saying `Error Plugin 'Activity Watcher' is incompatible with this installation.`
![error install plugin](https://user-images.githubusercontent.com/14180222/50340733-c3148280-054e-11e9-99e9-4bdc9ec8022e.png)

**Comment by OlivierMary** [comment]
Hi @edityomurti 

this plugin is available since 183.4284 of jetbrains tool if Android Studio 3.2.1 is based on lower version it will be incompatible.

If the version is good on https://developer.android.com/studio/#downloads it's based on 181.5056 so not compatible for plugin requirement. 

The plugin can work on 181.* I will try to fix that asap.

You can use IDEA 183 (20118.3)+ Android if you need that plugin now.

**Comment by OlivierMary** [comment]
Hi @edityomurti 
Can you test v1.0.5.181 ?

If good it will be avaible from Android sutdio when jetbrains accept the version.

**Comment by OlivierMary** [comment]
or v1.0.6

**Comment by OlivierMary** [comment]
Hi,

v1.0.7 was approved be jetbrains so you can install it from plugin search.

**Comment by edityomurti** [comment]
@OlivierMary v1.0.7
