### ISSUE TITLE
Plugin tracks Workspace.xml

### ISSUE THREAD

**Issue by ssoher** [OlivierMary/aw-watcher-jetbrains#24]
ActivityWatch dashboard Editor tab reports a high usage of Workspace.xml, is there a way to ignore this file as this must be an error since I never open that, it's used by the ide in the background?

I'm using the plugin with Rider 2019.2.3

**Comment by OlivierMary** [comment]
Hi, this plugin check only IDE Editor event (User event on openned files) so that strange to see this file.

Maybe another plugin change your workspace.xml ? Or Rider do it and send wrong events... 

I didn' t test with rider but editor's events are same for all jetbrains IDE.

I have a workspace.xml too in IDEA project and never see this file edited in AW.

Maybe check this file and how it change to understand why ?

**Comment by OlivierMary** [comment]
Hum an explanation if other user have same problem ? :)

**Comment by ssoher** [comment]
@OlivierMary Never happened since so probably human error. Vaguely remember opening it to see if I should ignore it in the repo and probably left it open when I went on a phone call or something is my guess.

**Comment by OlivierMary** [comment]
@ssoher ok tell me if that happen again :)
